---
- hosts: localhost
  gather_facts: False
  connection: local
  tasks:
    - name: Create a virtual machine from a template
      vmware_guest :
        hostname: "{{ vcenter_ip }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: False
        datacenter: Datacenter
        #cluster: cluster
        name: Test_VM_FTower
        state: poweredon
        template: rhel7template
        hardware:
          memory_mb: 2048
          num_cpus: 2
      register: create_vm_rg
      
