---
- hosts: localhost
  gather_facts: False
  connection: local
  tasks:
    - name: Create a virtual machine from a template
      vmware_guest:
        hostname: "{{ vcenter_ip }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: False
        datacenter: "{{ vmware_datacenter }}"
        #cluster: "{{ vmware_cluster }}"
        name: "{{ vm_name }}"
        state: poweredon
        template: "{{ vmware_template }}"
        wait_for_ip_address: no
        hardware:
          memory_mb: "{{ vm_ram  }}"
          num_cpus: "{{ vm_cpu }}"
      register: create_vm_rg
      #ignore_errors: True
      
